=== gryzly123/Integracja/LAB02/bus_stops.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://wi.zut.edu.pl/ia/bus_stops"
           xmlns="http://wi.zut.edu.pl/ia/bus_stops">

    <xs:element name="stops" type="bus_stops" />
    
    <xs:complexType name="bus_stops">
        <xs:sequence>
            <xs:element name="stop" type="bus_stop" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="bus_stop">
        <xs:sequence>
            <xs:element name="name"      type="xs:string" />
            <xs:element name="instances" type="stop_instances" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required" />
    </xs:complexType>

    <xs:complexType name="stop_instances">
	    <xs:sequence>
            <xs:element name="instance" type="stop_instance" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stop_instance">
	    <xs:sequence>
            <xs:element name="line" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== gryzly123/Integracja/rozwiazania/LAB02/bus_stops.xml
<?xml version="1.0" encoding="UTF-8"?>
<stops xmlns="http://wi.zut.edu.pl/ia/bus_stops"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://wi.zut.edu.pl/ia/bus_stops bus_stops.xsd">
    <stop id="1">
        <name>Żołnierska</name>
        <instances>
            <instance id="1">
				<line>7>Krzekowo</line>
				<line>5>Krzekowo</line>
			</instance>
            <instance id="2">
				<line>7>Truskawkowa</line>
				<line>5>Stocznia</line>
			</instance>
        </instances>
    </stop>
    <stop id="2">
        <name>Wernyhory</name>
        <instances>
            <instance id="1">
				<line>7>Krzekowo</line>
				<line>5>Krzekowo</line>
				<line>75>Krzekowo</line>
			</instance>
            <instance id="2">
				<line>7>Truskawkowa</line>
				<line>5>Stocznia</line>
			</instance>
			<instance id="3">
				<line>75>Dworzec Główny</line>
			</instance>
        </instances>
    </stop>
    <stop id="3">
        <name>Wyszyńskiego</name>
        <instances>
            <instance id="1">
				<line>7>Krzekowo</line>
				<line>5>Krzekowo</line>
				<line>75>Krzekowo</line>
			</instance>
            <instance id="2">
				<line>7>Truskawkowa</line>
				<line>5>Stocznia</line>
			</instance>
			<instance id="3">
				<line>75>Dworzec Główny</line>
			</instance>
			<instance id="4">
				<line>75>Dworzec Główny</line>
			</instance>

        </instances>
    </stop>
</stops>
