=== gryzly123/Integracja/integracja/src/main/java/eu/kniedzwiecki/integracja/books/books.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://wi.zut.edu.pl/ia/books"
           xmlns="http://wi.zut.edu.pl/ia/books">

    <xs:element name="books" type="books" />
    
    <xs:complexType name="books">
        <xs:sequence>
            <xs:element name="book" type="book" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="book">
        <xs:sequence>
            <xs:element name="title"        type="xs:string" />
            <xs:element name="authors"      type="authors" />
            <xs:element name="isbn"         type="xs:string" />
            <xs:element name="publisher"    type="xs:string" />
			<xs:element name="keywords"     type="xs:string" />
			<xs:element name="pages"        type="xs:int" />
			<xs:element name="year"         type="xs:int" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="authors">
        <xs:sequence>
            <xs:element name="author" type="xs:string" 
                        minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== gryzly123/Integracja/integracja/src/main/java/eu/kniedzwiecki/integracja/books/books.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://wi.zut.edu.pl/ia/books"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://wi.zut.edu.pl/ia/books books.xsd">
    <book id="TIXML">
        <title>Tablice informatyczne. XML</title>
        <authors>
            <author>Krzysztof Kozłowski</author>
            <author>Sławomir Zimosz</author>
        </authors>
        <isbn>83-246-0590-8</isbn>
        <publisher>Helion</publisher>
		<keywords>xml tablice</keywords>
		<pages>5</pages>
        <year>2007</year>
    </book>
    <book id="CWJAV3">
        <title>Java. Ćwiczenia praktyczne. Wydanie III</title>
        <authors>
            <author>Marcin Lis</author>
        </authors>
        <isbn>978-83-246-2785-1</isbn>
        <publisher>Helion</publisher>
		<keywords>java ćwiczenia</keywords>
		<pages>135</pages>
        <year>2011</year>
    </book>
    <book id="JAPPAN">
        <title>Java. Przygotowanie do programowania na platformę Android</title>
        <authors>
            <author>Jeff Friesen</author>
        </authors>
        <isbn>978-83-246-3372-2</isbn>
        <publisher>Helion</publisher>
		<keywords>java android</keywords>
		<pages>287</pages>
        <year>2011</year>
    </book>
</books>
